### ISSUE TITLE
Can't figure out how to run on ST2, Windows

### ISSUE THREAD

**Issue by emilyjrobinson** [zsong/diffy#10]
Hi, I'm trying to use Diffy on Sublime Text 2 on a Windows machine. I've installed the plugin and made sure it's enabled, but when I open two files and try to use the Window key commands, nothing happens. I can't figure out if I'm missing something really obvious or what. I'm a beginner with ST, so I'm not sure where to start troubleshooting. Any ideas? Thank you!

**Comment by zyfyy** [comment]
so do i..

**Comment by zsong** [comment]
Thanks for reporting the issue. 
Fixed in release 1.1.2. Will be live soon.
