### ISSUE TITLE
Add Diffy command to the Command Palette

### ISSUE THREAD

**Issue by certainlyakey** [zsong/diffy#4]
Hi, thanks for this plugin! Could you please add the Diffy command to the Sublime Text's command palette so it could be easily initiated. It's hard to remember a new shortcut.

**Comment by henrikba** [comment]
@certainlyakey - the flexibility of Sublime comes in handy;

In your `/Packages/User/Default.sublime-commands`, simply add
```json
[
 { "caption": "Diffy (remember; side-by-side)", "command": "diffy" },
 { "caption": "Diffy (cleanup)", "command": "diffy", "args": {"action": "clear"} },
]
```
This adds the two commands to the command palette, including displaying the keyboard shortcuts with it :smile:

**Comment by certainlyakey** [comment]
Thank you, henrikba!

**Comment by zsong** [comment]
@henrikba Thank you. Can you please create a pull request so I can merge your change?

**Comment by henrikba** [comment]
Unlikely ;) (I'm not a fluent git-hubber). Neither am I a Sublime wizard, but AFAIK, the `Default.sublime-commands` file can not be a part of your plugin. It is a common file outside the diffy plugin dir.

**Comment by riscie** [comment]
I added it to the context-menu and created a pull request. I am however pretty new to all this stuff, so please bear with me if what I am doing makes no sense...
