### ISSUE TITLE
Clear doesn't work with a single column

### ISSUE THREAD

**Issue by revolter** [zsong/diffy#9]
If I open two columns and use Diffy to mark the differences and then close the second column, clearing doesn't work until I open another column again.

**Comment by zsong** [comment]
Can't reproduce. Ctrl + K and Ctrl + C works for me.

**Comment by revolter** [comment]
@zsong Did you __CLOSE__ the second column (in other words, do you have __ONLY ONE__ column) before trying to clear the diff marks?

**Comment by zsong** [comment]
Oh ok. I see now. Will fix. Thanks again!

**Comment by revolter** [comment]
Sorry for the poor wording in the first comment. And no problem! Thank you too.
